[project]
name = "muradi-gartenbau-website"
version = "1.0.0"
description = "Eine responsive statische Website für Muradi Garten- und Landschaftsbau"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
]
